include: package:lints/recommended.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: false
    unnecessary_lambdas: true
    prefer_expression_function_bodies: false
